### ISSUE TITLE
Explanation about modded adbd binary 

### ISSUE THREAD

**Issue by matan7890** [tiann/adb_root#10]
Hey, just wondering how did you create the modded adbd binary file and whether it's possible to compile it by myself. I prefer to compile all opensource projects rather then download untrusted ones from the internet.

I would also suggest to create a Dockerfile for easier compile process and reproducible builds. The moment I'll understand what are all the tools and utilities needed to be compiled I'll gladly create one and add a PR.

**Comment by tiann** [comment]
Please check this https://github.com/tiann/adb_root/blob/main/build.sh
