### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [tiann/adb_root#3]
Thanks first for providing your module here! May I ask what license applies to it? And while on it, would you also provide an `update.json` (or make `version` match the corresponding tag name – currently the tag name cannot be easily derived from it as it doesn't contain the `version`) for easier automated updates?

**Comment by tiann** [comment]
1. LICENSE is GPLv3.
2. the version matches now.

**Comment by IzzySoft** [comment]
Thanks a lot! Added it to [my Magisk repo](https://apt.izzysoft.de/magisk) then, where it will show up with the next sync later today.
