### ISSUE TITLE
安装模块后无法在PC连接adb甚至mtp

### ISSUE THREAD

**Issue by natsumerinchan** [tiann/adb_root#9]
疑似是被selinux挡住了

root方案：KernelSU(11155)
内核版本：5.4.250-qgki-g6dd0584d
设备：一加9RT
ROM：类原生（PixelExperience）
模块版本：v1.1
日志：[KernelSU_bugreport_2023-07-25_23_14.tar.gz](https://github.com/tiann/adb_root/files/12162852/KernelSU_bugreport_2023-07-25_23_14.tar.gz)

**Comment by huangsijun17** [comment]
不同设备，也不用重复提交吧……
https://github.com/tiann/adb_root/issues/8

**Comment by natsumerinchan** [comment]
> 不同设备，也不用重复提交吧…… #8

我主要是看报错内容不一样才另开issue的

**Comment by huangsijun17** [comment]
> > 不同设备，也不用重复提交吧…… #8
> 
> 我主要是看报错内容不一样才另开issue的

就是同一个啊……我说的是电脑上什么设备都连不上。你说TPM和adb都连不上。这不同一个意思？

**Comment by natsumerinchan** [comment]
> > > 不同设备，也不用重复提交吧…… #8
> > 
> > 
> > 我主要是看报错内容不一样才另开issue的
> 
> 就是同一个啊……我说的是电脑上什么设备都连不上。你说TPM和adb都连不上。这不同一个意思？

我是指日志，你那里日志直接显示crash了，我这边显示的是被SELinux挡住了

```
avc: denied { open } for comm="adbd" path="/dev/__properties__" dev="tmpfs" ino=11158 scontext=u:r:adbd:s0 tcontext=u:object_r:properties_device:s0 tclass=dir permissive=1
```
